Repository NRLMMD-GEOIPS/data_fusion, pull requests merged in 2023-04, with the labels that each got.

#6 Update interface naming and move to plugins directory.
  .gitignore
  data_fusion/commandline/args.py
  data_fusion/plugins/modules/algorithms/stitched.py
  data_fusion/plugins/modules/output_formatters/layered_imagery.py
  data_fusion/plugins/modules/procflows/data_fusion.py
  data_fusion/plugins/yaml/product_inputs/abi.yaml
  data_fusion/plugins/yaml/product_inputs/ahi.yaml
  data_fusion/plugins/yaml/product_inputs/layered.yaml
  data_fusion/plugins/yaml/product_inputs/seviri.yaml
  data_fusion/plugins/yaml/product_inputs/stitched.yaml
  data_fusion/plugins/yaml/product_params/Layered-Winds-Horizontal-Adjust.yaml
  data_fusion/plugins/yaml/product_params/Layered-Winds-Horizontal-and-Vertical.yaml
  data_fusion/plugins/yaml/product_params/Layered-Winds-Vertical-Adjust.yaml
  data_fusion/plugins/yaml/product_params/Layered-Winds-Vertical-Default.yaml
  data_fusion/plugins/yaml/product_params/Layered.yaml
  docs/source/releases/CHANGELOG.md
  setup.py
  tests/scripts/geo.sh
  tests/scripts/layered.sh
Labels: refactor

#9 Resolving missing 1.9.0 updates from interface_modules -> plugins update
  data_fusion/plugins/modules/algorithms/stitched.py
  data_fusion/plugins/modules/output_formatters/layered_imagery.py
  data_fusion/plugins/modules/procflows/data_fusion.py
  docs/source/releases/CHANGELOG.md
  docs/source/releases/v1_10_0_dev0.rst
Labels: bug

#10 Update and rename v1_10_0_dev0.rst to v1_10_0a0.rst
  docs/source/releases/v1_10_0a0.rst
Labels: documentation
